-- Cau 2.1 --
CREATE TRIGGER Cau2_1_a
ON SV_DETAI
FOR INSERT
AS
	BEGIN
		DECLARE @MSSV CHAR(8), @SLDT INT
		SELECT @MSSV=MSSV FROM INSERTED
		SELECT @SLDT = COUNT(MSDT)
		FROM SV_DETAI
		WHERE MSSV=@MSSV
		IF (@SLDT>1)
			BEGIN
				PRINT N'Một sinh viên chỉ được tham gia một đề tài'
				ROLLBACK TRANSACTION
			END
	END
--
ALTER TABLE SV_DETAI
ADD CONSTRAINT UC_SV_DETAI_MSSV UNIQUE (MSSV);
-- Cau 2.2 --
ALTER TABLE GV_HDDT
ADD CONSTRAINT DIEM_GV_HDDT CHECK 
(DIEM BETWEEN 0 AND 10)

ALTER TABLE GV_UVDT
ADD CONSTRAINT DIEM_GV_UVDT CHECK 
(DIEM BETWEEN 0 AND 10)

ALTER TABLE GV_PBDT
ADD CONSTRAINT DIEM_GV_PBDT CHECK 
(DIEM BETWEEN 0 AND 10)
-- Cau 2.3 --
--Insert
CREATE TRIGGER Cau_2_3_INSERT
ON HOIDONG
FOR INSERT
AS
BEGIN
 DECLARE @MSGV CHAR(8), @MSHV INT
 SELECT @MSGV = MSGV FROM INSERTED
 SELECT @MSHV = MSHV
 FROM GV_HV_CN
 WHERE MSGV = @MSGV
 IF (@MSHV != 4)
 BEGIN
	 PRINT N'Giáo viên là chủ tịch hội đồng phải có học vị tiến sĩ'
	 ROLLBACK TRANSACTION
 END
END
--Update
CREATE TRIGGER Cau_2_3_UPDATE
ON HOIDONG
FOR update
AS
BEGIN
 DECLARE @MSGV CHAR(8), @MSHV INT
 SELECT @MSGV = MSGV FROM INSERTED
 SELECT @MSHV = MSHV
 FROM GV_HV_CN
 WHERE MSGV = @MSGV
 IF (@MSHV != 4)
 BEGIN
	 PRINT 'CHỦ TỊCH HỘI ĐỒNG PHẢI CÓ HỌC VỊ TIẾN SĨ'
	 ROLLBACK TRANSACTION
 END
END
--Delete
CREATE TRIGGER Cau_2_3_GV_HV_CN_delete
ON GV_HV_CN
FOR DELETE
AS
BEGIN
 IF (EXISTS (
 SELECT *
 FROM HOIDONG, deleted
 WHERE HOIDONG.MSGV = deleted.MSGV
 ))
 BEGIN
 DECLARE @MSHV INT
 SELECT @MSHV = MSHV FROM deleted
 IF (@MSHV = 4)
 BEGIN
	 PRINT N'Chủ tịch hội đồng phải có học vị tiến sĩ'
	 ROLLBACK TRANSACTION
 END
 END
END-- Cau 2.4 --CREATE PROCEDURE Cau_2_4
AS
BEGIN
 SELECT
 GIAOVIEN.MSGV,
 GIAOVIEN.TENGV,
 COUNT(DISTINCT CASE WHEN GV_PBDT.DIEM IS NOT NULL
THEN GV_PBDT.MSDT END) AS SoDeTaiPhanBien,
 COUNT(DISTINCT CASE WHEN GV_UVDT.DIEM IS NOT NULL
THEN GV_UVDT.MSDT END) AS SoDeTaiUyVien
 FROM GIAOVIEN
 LEFT JOIN GV_PBDT ON GIAOVIEN.MSGV = GV_PBDT.MSGV
 LEFT JOIN GV_UVDT ON GIAOVIEN.MSGV = GV_UVDT.MSGV
 GROUP BY GIAOVIEN.MSGV, GIAOVIEN.TENGV;
END

EXEC Cau_2_4
-- Cau 2.5 --
CREATE PROCEDURE DANH_SACH_SV_DTB_DE_TAI_CAO_NHAT
AS
BEGIN
    CREATE TABLE #SV_DIEMTB (
        MSSV CHAR(8) PRIMARY KEY,
        DIEMTB FLOAT
    );

    INSERT INTO #SV_DIEMTB (MSSV, DIEMTB)
    SELECT 
        SV.MSSV, 
        COALESCE(
            (SUM(GV_HDDT.DIEM) + SUM(GV_PBDT.DIEM) + SUM(GV_UVDT.DIEM)) / 
            NULLIF((COUNT(GV_HDDT.MSGV) + COUNT(GV_PBDT.MSGV) + COUNT(GV_UVDT.MSGV)), 0), 
        0) AS DIEMTB
    FROM SINHVIEN AS SV
    LEFT JOIN SV_DETAI ON SV.MSSV = SV_DETAI.MSSV
    LEFT JOIN GV_HDDT ON SV_DETAI.MSDT = GV_HDDT.MSDT
    LEFT JOIN GV_UVDT ON SV_DETAI.MSDT = GV_UVDT.MSDT
    LEFT JOIN GV_PBDT ON SV_DETAI.MSDT = GV_PBDT.MSDT
    GROUP BY SV.MSSV;

    SELECT SV.TENSV, #SV_DIEMTB.DIEMTB
    FROM SINHVIEN AS SV
    INNER JOIN #SV_DIEMTB 
    ON SV.MSSV = #SV_DIEMTB.MSSV
    WHERE #SV_DIEMTB.DIEMTB = (SELECT MAX(DIEMTB) FROM #SV_DIEMTB);

    DROP TABLE #SV_DIEMTB;
END;
EXEC DANH_SACH_SV_DTB_DE_TAI_CAO_NHAT-- Cau 3.1 --CREATE LOGIN GIANGVIEN WITH PASSWORD = '12345'CREATE LOGIN GIAOVU WITH PASSWORD = '12345'CREATE LOGIN SINHVIEN WITH PASSWORD = '12345'CREATE USER GIANGVIEN FOR LOGIN GIANGVIENCREATE USER GIAOVU FOR LOGIN GIAOVUCREATE USER SINHVIEN FOR LOGIN SINHVIEN-- Cau 3.2 --EXEC sp_addrolemember 'db_datareader', 'GIAOVU'EXEC sp_addrolemember 'db_datawriter', 'GIAOVU'DENY DELETE ON DATABASE::QUANLYDETAIBTTTH2 TO GIAOVUGRANT SELECT ON GIAOVIEN TO GIANGVIENGRANT SELECT ON DETAI TO GIANGVIENGRANT SELECT ON SV_DETAI TO GIANGVIENGRANT SELECT ON HOIDONG TO GIANGVIENGRANT SELECT ON HOIDONG_GV TO GIANGVIENGRANT UPDATE ON GIAOVIEN TO GIANGVIENGRANT SELECT ON SINHVIEN TO SINHVIENGRANT SELECT ON DETAI TO SINHVIENGRANT SELECT ON HOIDONG TO SINHVIENDENY DELETE TO GIAOVUDENY DELETE TO GIANGVIENDENY DELETE TO SINHVIEN